"""add status column and index

Revision ID: 99bae3f947d2
Revises: 6e6f2ca4d05c
Create Date: 2025-04-25 14:58:29.891938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99bae3f947d2'
down_revision: Union[str, None] = '6e6f2ca4d05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_envelopes', sa.Column('status', sa.String(), server_default='received', nullable=False))
    op.alter_column('message_envelopes', 'status', server_default=None)
    op.create_index('ix_message_envelopes_status', 'message_envelopes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_envelopes_status', table_name='message_envelopes')
    op.drop_column('message_envelopes', 'status')
    # ### end Alembic commands ###
